Homework1
mishakras/pythontrainning pull request #1
Opened 2021-08-27 13:17 UTC by mishakras

2021-08-29 12:48 UTC, mishakras commented on homework1/task5.py
> +def find_maximal_subarray_sum(nums: List[int], k: int) -> int:
Fixed, I assumed that order of elements of array doesn't matter.

2021-08-29 12:52 UTC, mishakras commented on homework1/task4.py
> +def check_sum_of_four(a: List[int], b: List[int], c: List[int],
Added some check for early ending, best case is O(n*log (N)), worst still O(N^4).

2021-08-29 12:52 UTC, mishakras commented on homework1/task3.py
> +We guarantee, that file exists and contains line-delimited integers.
Fixed

2021-08-29 12:56 UTC, mishakras commented on homework1/task2.py
> +def check_fibonacci(data: Sequence[int]) -> bool:
Do you want strict fibonacchi sequence, a.i. 1,1,2,3,5... or any that follows Yn=Y(n-1)+Y(n-2)? Later works.

2021-08-29 14:37 UTC, nikitosboroda requested changes

2021-08-29 14:37 UTC, nikitosboroda commented on homework1/task2.py
> +def check_fibonacci(data: Sequence[int]) -> bool:
strict
better 0, 1, 1, 2 ...

2021-08-31 05:44 UTC, nikitosboroda approved these changes

2021-08-31 10:19 UTC, merged